spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5439/labprog}
    username: ${DB_URL:postgres}
    password: ${DB_PASSWORD:123456}
  devtools:
    restart:
      enabled: false