spring:
    application:
        name: portal-egresso
    
    profiles:
        active: ${APP_PROFILE:test}

    jpa:
        open-in-view: false


    devtools:
        remote:
            secret: 123456