spring:
  jpa:
  #  properties:
  #    jakarta:
  #      persistence:
  #        schema-generation:
  #          create-source: metadata
  #          scripts:
  #            action: create
  #            create-target: create.sql
  #    hibernate:
  #      hbm2ddl:
  #        delimiter: ;
  #      jdbc:
  #        lob:
  #          non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5438/labprog
    username: postgres
    password: 123456
  #sql:
  #  init:
  #    mode: always
  #    data-locations: classpath:import.sql
  #    platform: postgresql